// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Note_Taking_App.Data;

#nullable disable

namespace Note_Taking_App.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Note_Taking_App.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Milk,Bread,Chicken,Juice",
                            Date = new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "grocery"
                        },
                        new
                        {
                            Id = 2,
                            Content = "hjwoivhjcwifj",
                            Date = new DateTime(2024, 8, 2, 17, 57, 2, 244, DateTimeKind.Local).AddTicks(8872),
                            Title = "vhudhuwf"
                        },
                        new
                        {
                            Id = 3,
                            Content = "jf9wjfiqw",
                            Date = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            Title = "wjijewif"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
